### ISSUE TITLE
烦请增加SSH加密算法

### ISSUE THREAD

**Issue by laiyh31** [jumpserver/docs#11]
版本：1.5.0－2
情况：组件koko，使用SSH连接华为路由设备时，因不支持AES－CBC导致连接失败。
提示信息：
Connect asset A-ME60 error: ssh: handshake failed: ssh: no common algorithm for client to server cipher; client offered: [aes128-gcm@openssh.com chacha20-poly1305@openssh.com aes128-ctr aes192-ctr aes256-ctr], server offered: [aes256-cbc aes128-cbc 3des-cbc des-cbc]

**Comment by wojiushixiaobai** [comment]
@laiyh31 2333，问题都问到这里来了。。

把镜像更新下再试试，有问题再继续提

**Comment by laiyh31** [comment]
几天前才刚刚装的，镜像应该是最新版吧


------------------ 原始邮件 ------------------
发件人: "wojiushixiaobai"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 下午3:21
收件人: "jumpserver/docs"<docs@noreply.github.com>;
抄送: "lyh31"<121952736@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [jumpserver/docs] 烦请增加SSH加密算法 (#11)




@laiyh31 2333，问题都问到这里来了。。
 
把镜像更新下再试试，有问题再继续提

**Comment by wojiushixiaobai** [comment]
@laiyh31 可以关注下镜像主页，修复bug就会更新
