### ISSUE TITLE
建议更新下文档目录结构

### ISSUE THREAD

**Issue by maninhill** [jumpserver/docs#141]
总体介绍 -> 原来叫主页
安装配置
管理文档
用户文档 -_> **位置上移，这部分比较重要**_
开发文档 _-> **位置下移**_
常见问题 
        - Core 常见问题
        - Luna 常见问题
        - koko 常见问题
        - Guamodule 常见问题 
        - 其他已知问题 _-> **问题清单改名其他已知问题，并移动到这里**_
关于

**Comment by maninhill** [comment]
总体介绍 -> 原来叫主页
安装配置
管理文档
用户文档 -> 位置上移，这部分比较重要
开发文档 -> 位置下移
常见问题
     已知问题 -> 问题清单改名已知问题，并移动到这里
     Core 常见问题
     Luna 常见问题
     koko 常见问题
     Guamodule 常见问题
关于

**Comment by wojiushixiaobai** [comment]
问题清单需要经常被访问，不适合下潜到二级目录。
开发文档应该为管理和开发人员使用，所以放在管理文档下方。

**Comment by maninhill** [comment]
明白。问题清单，我理解英文是 Known Issues，一般人们叫做，已知问题，是否会比较合适？

**Comment by wojiushixiaobai** [comment]
@maninhill 问题清单这个列表的用途是针对当前未能解决的问题做通报（包含安全类），让管理员和开发者能及时看到。解决后说明什么版本开始解决及如何解决。这个词是从 jira 里面 get 的。帮助文档后期下面还会有其他的模块，比如二次开发方面的。

**Comment by wojiushixiaobai** [comment]
问题划分为，用户操作失误的问题—>常见问题
安全类、bug或者不稳定的功能—>问题清单

叫已知问题也不太适合，后面里面的内容多了可能需要分类，比如安全类，bug类

**Comment by maninhill** [comment]
好的，辛苦小白了。
