### ISSUE TITLE
文档Logo 和主题色更改

### ISSUE THREAD

**Issue by maninhill** [jumpserver/docs#144]
![image](https://user-images.githubusercontent.com/41712985/82133424-8a014000-981e-11ea-8b65-63cc6c843565.png)

Logo 图片：
[JumpServer-辅助图形-反白.png.zip](https://github.com/jumpserver/docs/files/4639486/JumpServer-.-.png.zip)

**Comment by wojiushixiaobai** [comment]
已合并

**Comment by maninhill** [comment]
赞
